global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'agriconnect-annuaire'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8761']

  - job_name: 'apigateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:10000']

  - job_name: 'configservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:10002']

  - job_name: 'agriconnect-actionneurs'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:10003']

  - job_name: 'agriconnect-capteur'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:10004']

  - job_name: 'ac-releve'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:10005']

  - job_name: 'agriconnect-dataschedule'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:10006']

  - job_name: 'agriconnect-capteur-releve'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:10007']

  - job_name: 'agriconnect-utilisateur'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:10008' ]

